#Used by classifier and class_generator
features_topic: "/audio_features_extraction/features"
#Used by train and classifier
classifier_name: 'modelSVM'
#Used by train and visualize
classes:
  silence
  water_v1
  water_v2
  engine
  cars
  cars_right
  cars_left
#Used by class_generator
current_class: test #class to be added NOW by class_generator
#Used by classifier
classification_topic: "audio_classification"
